### ISSUE TITLE
Implement upload options

### ISSUE THREAD

**Issue by tassia** [hotosm/oam-qgis-plugin#21]
- Notify OAM of new resource
- Trigger OAM tile service
- Reproject to EPSG:3857
- Convert format to GeoTIFF RGB

**Comment by cgiovando** [comment]
As discussed in #25, both "Reproject to EPSG:3857" and "Convert format to GeoTIFF RGB" will move to the metadata tab.

Please coordinate with @smit1678 to understand how to notify OAM Catalog of new resources added.

And with @mojodna and @lossyrob on how to trigger the tile map service creation with OAM Server.

**Comment by smit1678** [comment]
Just posted some related information in https://github.com/hotosm/oam-catalog/issues/49 on the catalog. But based on the uploader work, notifying the catalog could just be cut from scope.

**Comment by tassia** [comment]
News from @modjona:
https://github.com/hotosm/oam-server-api/pull/7

**Comment by tassia** [comment]
all done.
