### ISSUE TITLE
Implement edit settings window (wishlist)

### ISSUE THREAD

**Issue by tassia** [hotosm/oam-qgis-plugin#22]
This will allow the user to define default settings and metadata without the need to access the file in the file system.

**Comment by cgiovando** [comment]
Defaults should be available to avoid re-entering common metadata for images. They can either be set in a "Settings" menu or read from previous entries.

**Comment by tassia** [comment]
If we change the layout for a wizard, the settings should appear in a separate widget, not as simply a separate tab.

**Comment by tassia** [comment]
The design for the "Edit settings" dialog was created. It is not functional yet though.

**Comment by tassia** [comment]
done, thanks to @yojiyojiyoji
