### ISSUE TITLE
Review design of tabs

### ISSUE THREAD

**Issue by tassia** [hotosm/oam-qgis-plugin#25]
Maybe we could add some instruction on top of each tab (just a short sentence). The metadata review could go on a separate tab, since reading multiple metadata can be painful in such a small widget. And the last tab would have more space for other upload options and input of bucket credentials.

**Comment by tassia** [comment]
After some discussion, we've decided the upload options should come before the metadata review, since the options can actually affect the metadata (for instance, reprojection).

**Comment by cgiovando** [comment]
As agreed, let's just move the re-projection and conversion options to the metadata editing tab. They will be applied per input image

Before execution there needs to be some check whether the input files are already in EPSG:3857 and GeoTIFF or not. Even better if the option become available only when it's not the case. In the case they already are, then those options would be greyed out.

**Comment by tassia** [comment]
After showing the design to more people and having good feedbacks, I'm convinced that we should move for a wizard design instead of tabs.
