### ISSUE TITLE
Test plugin in Mac OS X

### ISSUE THREAD

**Issue by cgiovando** [hotosm/oam-qgis-plugin#34]

**Comment by tassia** [comment]
Basic testing was done, more to come post-outreachy.

**Comment by yojiyojiyoji** [comment]
It should be working fine, but need to make sure that GDAL is installed by the recommended way (http://www.qgis.org/en/site/forusers/download.html).
Installation of GDAL through Homebrew is not currently supported for the version 0.1-alpha.
