### ISSUE TITLE
Review sources metadata not working in QGIS 2.8.2 on Mac OSX

### ISSUE THREAD

**Issue by cgiovando** [hotosm/oam-qgis-plugin#37]
The window where the user should be able to review each metadata entry is currently blank. Can you confirm it works on other platforms?

**Comment by tassia** [comment]
Yes, I confirm it works in my platform. We need to find a way to debug on Mac OSX, cause not only this but the widget to load layers seem to not be working as well. So maybe the bug is related to the kind of text widget. To be investigated.

**Comment by cgiovando** [comment]
It works now ;-)
