### ISSUE TITLE
Implement Search and Browse Functionalities

### ISSUE THREAD

**Issue by cgiovando** [hotosm/oam-qgis-plugin#74]
A placeholder to keep track of ideas for implementing search and browse functions.  

* allow seamless overlay of image search results with already opened QGIS layers
* search results should be displayed dynamically in the same window of the search/filter functions
* this portion of the plugin should have similar functionalities that are available in the OAM Browser
 * filter based on metadata
 * sort of results
 * footprints and image overviews

**Comment by yojiyojiyoji** [comment]
move to #87
